### ISSUE TITLE
Problem with updating EYA Records 

### ISSUE THREAD

**Issue by romalozhkin00001** [mirrorfm/data#127]
In last couple months a lot of great releases were uploaded to Spotify. For example: 
https://open.spotify.com/album/7HBu7DjIUQFHrnkGX50pyJ?si=uSPF3--cQFKL8OxsxyNPzA
https://open.spotify.com/album/6ZQTZZNaD7sa2WFcJnB55s?si=2k0RHo-3QRyuH6YChRzOtQ
https://open.spotify.com/album/6vJU0wXoK606Gne4MiAwGa?si=uOCoYE_ASl-cdoNQ7RZXkQ

But I can't find it in that playlist 
https://open.spotify.com/playlist/5atajczRCOylx8uv9DNpBt?si=d8cfaefac3064b83

**Comment by romalozhkin00001** [comment]
@stephanebruckert HI! Could you please check it?

**Comment by stephanebruckert** [comment]
@romalozhkin00001 thanks for reporting this. Discogs search was stuck, this fixed it https://github.com/mirrorfm/core/commit/b6d9c765afc3a6fb76224e17da23cd244e56a4f2

This label playlist is now up-to-date. Just the first [album](https://open.spotify.com/album/7HBu7DjIUQFHrnkGX50pyJ?si=uSPF3--cQFKL8OxsxyNPzA) wasn't found because the [discogs release](https://www.discogs.com/release/16121649-Zots-Sleepshop-EP) uses a different artist name. But that's a different problem.

All other labels will also update sooner or later.
